.PHONY: all clean
all:
	$(MAKE) -C common $(MAKEFLAGS)
	$(MAKE) -C controller $(MAKEFLAGS)
#	$(MAKE) -C robot $(MAKEFLAGS)
clean:
	$(MAKE) -C common $(MAKEFLAGS) clean
	$(MAKE) -C controller $(MAKEFLAGS) clean
#	$(MAKE) -C robot $(MAKEFLAGS) clean
